export const ADD_TO_CART ='ADD_TO_CART';
export const REMOVE_TO_CART ='REMOVE_TO_CART';
export const ADD_TO_WISHLIST ='ADD_TO_WISHLIST';
export const REMOVE_TO_WISHLIST ='REMOVE_TO_WISHLIST';

export const ADD_ADDRESS = 'ADD_ADDRESS';
export const DELETE_ADDRESS = 'DELETE_ADDRESS';