export const products = {
  category: [
    {
      id:1,
      category: 'T Shirt',
      data: [
        {
          id:1,
          name: 't-shirt 1',
          price: 300,
          gender: 'male',
          image: require('./images/tshirt1.jpg'),
        },
        {
          id:2,
          name: 't-shirt 2',
          price: 349,
          gender: 'male',
          image: require('./images/tshirt2.jpeg'),
        },
        {
          id:3,
          name: 't-shirt 3',
          price: 200,
          gender: 'male',
          image: require('./images/tshirt3.webp'),
        },
        {
          id:4,
          name: 't-shirt 4',
          price: 299,
          gender: 'male',
          image: require('./images/tshirt4.webp'),
        },
        {
          id:5,
          name: 't-shirt 5',
          price: 399,
          gender: 'male',
          image: require('./images/tshirt5.webp'),
        },
      ],
    },
    {
      id:2,
      category: 'Jeans',
      data: [
        {
          id:6,
          name: 'Jeans 1',
          price: 500,
          gender: 'male',
          image: require('./images/jeans1.webp'),
        },
        {id:7,
          name: 'Jeans 2',
          price: 499,
          gender: 'male',
          image: require('./images/jeans2.webp'),
        },
        {id:8,
          name: 'Jeans 3',
          price: 599,
          gender: 'male',
          image: require('./images/jeans3.jpeg'),
        },
        {
          id:9,
          name: 'Jeans 4',
          price: 699,
          gender: 'male',
          image: require('./images/jeans4.webp'),
        },
      ],
    },
    {id:3,
      category: 'Shoes',
      data: [
        {
          id:10,
          name: 'Shoes 1',
          price: 1100,
          gender: 'male',
          image: require('./images/shoes1.jpeg'),
        },
        {
          id:11,
          name: 'Shoes 2',
          price: 680,
          gender: 'male',
          image: require('./images/shoes2.jpeg'),
        },
        {
          id:12,
          name: 'Shoes 3',
          price: 599,
          gender: 'male',
          image: require('./images/shoes3.jpeg'),
        },
        {
          id:13,
          name: 'Shoes 4',
          price: 800,
          gender: 'male',
          image: require('./images/shoes4.jpeg'),
        },
        {
          id:14,
          name: 'Shoes 5',
          price: 1000,
          gender: 'male',
          image: require('./images/shoes5.webp'),
        },
      ],
    },
    {
      id:4,
      category: 'Jacket',
      data: [
        {id:14,
          name: 'Jacket 1',
          price: 1300,
          gender: 'male',
          image: require('./images/jacket1.webp'),
        },
        {
          id:15,
          name: 'Jacket 2',
          price: 999,
          gender: 'male',
          image: require('./images/jacket2.webp'),
        },
        {
          id:16,
          name: 'Jacket 3',
          price: 650,
          gender: 'male',
          image: require('./images/jacket3.webp'),
        },
        {
          id:17,
          name: 'Jacket 4',
          price: 800,
          gender: 'male',
          image: require('./images/jacket4.webp'),
        },
      ],
    },
    {
      id:5,
      category: 'Slipper',
      data: [
        {
          id:18,
          name: 'Slippers 1',
          price: 250,
          gender: 'male',
          image: require('./images/slipper1.webp'),
        },
        {
          id:19,
          name: 'Slipper 2',
          price: 450,
          gender: 'male',
          image: require('./images/slipper2.webp'),
        },
        {
          id:20,
          name: 'Slipper 3',
          price: 400,
          gender: 'male',
          image: require('./images/slipper3.jpeg'),
        },
        {
          id:21,
          name: 'Slipper 4',
          price: 240,
          gender: 'male',
          image: require('./images/slipper4.jpeg'),
        },
        {
          id:22,
          name: 'Slipper 5',
          price: 399,
          gender: 'male',
          image: require('./images/slipper5.jpeg'),
        },
      ],
    },
    {
      id:6,
      category: 'Trousers',
      data: [
        {
          id:23,
          name: 'Trousers 1',
          price: 250,
          gender: 'male',
          image: require('./images/trouser1.jpg'),
        },
        {
          id:24,
          name: 'Trousers 2',
          price: 450,
          gender: 'male',
          image: require('./images/trouser2.webp'),
        },
        {
          id:25,
          name: 'Trousers 3',
          price: 400,
          gender: 'male',
          image: require('./images/trouser3.webp'),
        },
        {id:26,
          name: 'Trousers 4',
          price: 240,
          gender: 'male',
          image: require('./images/trouser4.jpeg'),
        },
        {
          id:27,
          name: 'Trousers 5',
          price: 399,
          gender: 'male',
          image: require('./images/trouser5.jpeg'),
        },
      ],
    },
  ],
};